### ISSUE TITLE
Notification Channel fails Android 7.1.1

### ISSUE THREAD

**Issue by agrw** [NativeScript/sample-android-background-services#26]
but the notification code doesn't work with Android 7.1.1
  const mChannel = new android.app.NotificationChannel(channelId, name,importance);

**Comment by fabiomela** [comment]
Same issue on the example project.

`StackTrace: 
System.err: 	Frame: function:'onStartJob', file:'file:///data/data/org.nativescript.bgservice/files/app/notifications/MyJobService.js', line: 29, column: 26
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.notifications.MyJobService.onStartJob(MyJobService.java:13)
System.err: 	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:143)
System.err: 	... 6 more
System.err: Caused by: java.lang.ClassNotFoundException: android.app.NotificationChannel
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:400)
System.err: 	at java.lang.Class.forName(Class.java:326)
System.err: 	at com.tns.Runtime.getClassForName(Runtime.java:1010)
System.err: 	at com.tns.ClassResolver.resolveClass(ClassResolver.java:46)
System.err: 	at com.tns.Runtime.resolveClass(Runtime.java:581)
System.err: 	... 14 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/org.nativescript.bgservice-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.bgservice-1/lib/x86, /data/app/org.nativescript.bgservice-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err: 	... 20 more
`

**Comment by skhye05** [comment]
I am getting the same issue.

**Comment by ju4nj3** [comment]
+1

**Comment by NickIliev** [comment]
@ju4nj3  @skhye05  @agrw @fabiomela 

The demo will work only on Android 8 and above. I've added [a note in the README ](https://github.com/NativeScript/sample-android-background-services/pull/30). To support an earlier versions you will need to remove the `NotificationChannel` usage.

Also added Webpack to the demo.

**Comment by ju4nj3** [comment]
Thank you @NickIliev
